services:
  - type: web
    name: clothing-shop
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn amazon.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DJANGO_DEBUG
        value: False
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: clothing-db
          property: connectionString
    autoDeploy: true

databases:
  - name: clothing-db
    databaseName: clothing_shop
    user: clothing_user
